export const services = [
  {
    id: 'staffing',
    num: '01',
    title: 'Staffing, VA & Recruitment',
    subtitle: 'People Operations',
    description: 'Expert staffing solutions combining deep talent databases with strategic RPO. Our virtual assistants and recruitment specialists integrate seamlessly with your workflow — reducing time-to-hire and total cost.',
    highlight: null,
    tags: ['RPO', 'Virtual Assistant', 'Recruitment', 'Talent Sourcing', 'HR Outsourcing'],
    items: [
      'Recruitment Process Outsourcing (RPO)',
      'Virtual Assistant placement & management',
      'Executive & specialist talent sourcing',
      'Resume screening & candidate shortlisting',
      'Onboarding coordination & documentation',
      'Contract & permanent staffing solutions',
      'Bulk hiring & high-volume recruitment',
    ],
  },
  {
    id: 'data',
    num: '02',
    title: 'Data & Excel',
    subtitle: 'Data Operations',
    description: 'End-to-end data management: entry, processing, conversion, and Excel automation. We handle high-volume, time-critical data workflows with consistent 99% accuracy — freeing your team for higher-value work.',
    highlight: null,
    tags: ['Data Entry', 'Excel', 'OCR / ICR', 'Data Conversion', 'Automation'],
    items: [
      'High-volume data entry & verification',
      'Excel automation, formulas & macros',
      'OCR / ICR processing for scanned documents',
      'PDF & document data extraction',
      'Database cleaning & deduplication',
      'Data conversion between formats',
      'Online & offline form processing',
    ],
  },
  {
    id: 'qa',
    num: '03',
    title: 'QA Testing — App & Web',
    subtitle: 'Quality Assurance',
    description: 'Comprehensive manual QA services for web and mobile applications. We specialise in hands-on, user-based testing — replicating real-world interactions to surface bugs before your users do.',
    highlight: 'Unlike automated tools, our human testers catch UX issues, visual regressions, and edge cases that scripts miss — delivering a truly production-ready product.',
    tags: ['Manual QA', 'Web Testing', 'Mobile Testing', 'Regression', 'Accessibility'],
    items: [
      'Manual functional & regression testing',
      'Cross-browser & cross-device testing',
      'Mobile app testing (iOS & Android)',
      'User acceptance testing (UAT)',
      'Accessibility & WCAG compliance checks',
      'Test case writing & documentation',
      'Bug reporting with detailed reproduction steps',
    ],
  },
  {
    id: 'dataeng',
    num: '04',
    title: 'Data Engineering & Visualizations',
    subtitle: 'Data Infrastructure',
    description: 'Transform raw data into strategic intelligence. We architect modern Data Lakehouse solutions on Snowflake, Databricks & Microsoft Fabric — and deliver actionable insights through Power BI and Tableau dashboards.',
    highlight: null,
    tags: ['Snowflake', 'Databricks', 'Microsoft Fabric', 'Power BI', 'Tableau', 'ETL'],
    items: [
      'Data Lakehouse architecture & setup',
      'Snowflake, Databricks, Microsoft Fabric',
      'ETL / ELT pipeline development',
      'Power BI dashboard & report creation',
      'Tableau visualizations & analytics',
      'Data modelling & warehouse design',
      'Ongoing pipeline maintenance & optimisation',
    ],
  },
]
