export const services = [
  {
    id: 'staffing',
    num: '01',
    title: 'Staffing & VA Recruitment',
    subtitle: 'People Operations',
    benefitHeadline: 'Hire faster. Pay less. Stop wasting time on bad candidates.',
    description: 'We source, screen, and place qualified candidates and virtual assistants — so your team spends time closing deals, not reading CVs. Average time-to-hire: under 7 days.',
    outcomes: [
      'Cut time-to-hire by up to 60% with pre-screened candidate pipelines',
      'Reduce hiring costs by 40–70% vs. traditional recruitment agencies',
      'VA placement with 30-day performance guarantee — or we replace at no cost',
    ],
    bestFor: 'Startups and SMBs scaling their team, companies with ongoing recruitment needs, businesses looking to replace expensive local hires with skilled remote talent.',
    highlight: null,
    tags: ['RPO', 'Virtual Assistant', 'Recruitment', 'Talent Sourcing', 'HR Outsourcing'],
    items: [
      'Recruitment Process Outsourcing (RPO)',
      'Virtual Assistant placement & management',
      'Executive & specialist talent sourcing',
      'Resume screening & candidate shortlisting',
      'Onboarding coordination & documentation',
      'Contract & permanent staffing solutions',
      'Bulk hiring & high-volume recruitment',
    ],
  },
  {
    id: 'data',
    num: '02',
    title: 'Data Entry & Excel Automation',
    subtitle: 'Data Operations',
    benefitHeadline: 'Eliminate data backlogs. Get clean, accurate data — fast.',
    description: 'We handle your high-volume data entry, document processing, and Excel automation with 99% accuracy — freeing your team from repetitive work and eliminating costly errors.',
    outcomes: [
      'Process thousands of records daily with guaranteed 99%+ accuracy',
      'Automate repetitive Excel tasks — reduce manual processing time by 80%',
      'Same-day turnaround available for urgent, time-critical data projects',
    ],
    bestFor: 'Finance, legal, healthcare, and logistics companies handling large volumes of structured data, forms, invoices, or documents that need fast, accurate processing.',
    highlight: null,
    tags: ['Data Entry', 'Excel Automation', 'OCR / ICR', 'Data Conversion', 'Document Processing'],
    items: [
      'High-volume data entry & verification',
      'Excel automation, formulas & macros',
      'OCR / ICR processing for scanned documents',
      'PDF & document data extraction',
      'Database cleaning & deduplication',
      'Data conversion between formats',
      'Online & offline form processing',
    ],
  },
  {
    id: 'qa',
    num: '03',
    title: 'Manual QA Testing',
    subtitle: 'Quality Assurance',
    benefitHeadline: "Ship software that works. Every browser, every device, every time.",
    description: 'Our human QA testers find the bugs, UX issues, and edge cases that automated tools miss — before your users do. We test like real users, not like scripts.',
    outcomes: [
      'Catch critical bugs before launch — reduce post-release fixes by up to 70%',
      'Full cross-browser and cross-device coverage in a single test cycle',
      'Detailed bug reports with reproduction steps, screenshots, and severity ratings',
    ],
    bestFor: 'SaaS companies, app developers, and agencies shipping new features or releases who need thorough human testing without the cost of an in-house QA team.',
    highlight: 'Unlike automated tools, our human testers catch UX issues, visual regressions, and real-world edge cases that scripts always miss.',
    tags: ['Manual QA', 'Cross-browser Testing', 'Mobile Testing', 'UAT', 'Regression Testing'],
    items: [
      'Manual functional & regression testing',
      'Cross-browser & cross-device testing',
      'Mobile app testing (iOS & Android)',
      'User acceptance testing (UAT)',
      'Accessibility & WCAG compliance checks',
      'Test case writing & documentation',
      'Bug reporting with detailed reproduction steps',
    ],
  },
  {
    id: 'dataeng',
    num: '04',
    title: 'Data Engineering & BI Dashboards',
    subtitle: 'Data Infrastructure',
    benefitHeadline: 'Turn raw data into decisions. Build your data stack — done right.',
    description: 'We architect, build, and maintain modern data infrastructure on Snowflake, Databricks, and Microsoft Fabric — and deliver clear Power BI and Tableau dashboards your leadership can actually use.',
    outcomes: [
      'Get a production-ready data lakehouse in weeks, not months',
      'Consolidate siloed data sources into a single source of truth',
      'Deliver real-time dashboards that reduce reporting time from days to minutes',
    ],
    bestFor: 'Mid-market and enterprise companies drowning in disconnected data, teams spending hours on manual reports, and businesses ready to make data-driven decisions at scale.',
    highlight: null,
    tags: ['Snowflake', 'Databricks', 'Microsoft Fabric', 'Power BI', 'Tableau', 'ETL Pipelines'],
    items: [
      'Data Lakehouse architecture & setup',
      'Snowflake, Databricks, Microsoft Fabric',
      'ETL / ELT pipeline development',
      'Power BI dashboard & report creation',
      'Tableau visualizations & analytics',
      'Data modelling & warehouse design',
      'Ongoing pipeline maintenance & optimisation',
    ],
  },
]
